KTOR-6741 Part 1 - Replace "Creating HTTP API's tutorial" with a new tutorial "Handle requests and generate responses"
ktorio/ktor-documentation pull request #421
Opened 2024-02-06 17:02 UTC by vnikolova

[KTOR-6741](https://youtrack.jetbrains.com/issue/KTOR-6741/Replace-Creating-HTTP-APIs-tutorial-with-new-content)

The "Creating HTTP APIs" tutorial will be replaced by two new tutorials:

1. Handle requests and generate responses. (orig. [Understanding Routing and Requests](https://docs.google.com/document/d/10XH3fwAG8GY1s6BydU8tVH0Dtxek29sPuwavYfT3Tk0/edit?usp=sharing))
2. Create RESTful APIs that generate JSON. (orig. [Content Negotiation and REST](https://docs.google.com/document/d/1Ekah3oGHz50wO2pis65l1hQllHXKfX7uQSUWOK9uXKc/edit?usp=sharing))

In this PR:
[See preview on staging](https://ktor.shared.aws.intellij.net/docs/handle-requests-and-generate-responses.html)
- [x] Both new topics are added and placed in the navigation
- [x]  "Creating HTTP APIs" is removed
- [x]  Content is added for "Handle requests and generate responses" tutorial with screenshots for light and dark theme
- [x]  An example project is added

The "Create RESTful APIs that generate JSON." topic is currently empty. It will be covered in a separate PR, to be merged to `main` later with this one.

2024-02-13 08:02 UTC, e5l commented
some screenshots are flying :) 
<img width="685" alt="image" src="https://github.com/ktorio/ktor-documentation/assets/4290035/838be474-1344-41f6-a349-a70394a6fd6b">

2024-02-13 08:04 UTC, e5l requested changes
Good job, it looks really nice! Please check some minor comments.

I also noticed that screenshots are only for the dark theme now

2024-02-13 08:04 UTC, e5l commented on codeSnippets/snippets/tutorial-server-routing-and-requests/src/main/kotlin/model/TaskRepository.kt
> +    fun tasksByPriority(priority: Priority) = tasks.filter {
I would keep an empty line between methods for readability; you can invoke autoformat in IDEA or use detekt plugin, they can fix it

2024-02-13 08:04 UTC, e5l commented on topics/handle-requests-and-generate-responses.topic
> +                <p>Open the
<img width="394" alt="image" src="https://github.com/ktorio/ktor-documentation/assets/4290035/2fbe363c-d91d-46f2-b936-61008977dabb">

code blocks merged

2024-02-13 10:12 UTC, vnikolova commented on topics/handle-requests-and-generate-responses.topic
> +    <chapter title="Iteration 1: Display static HTML content" id="iteration-1">
Or, what do you think about removing "Iteration {n}:"  from the titles altogether? I don't see it as a common practice to have either one in the title.

2024-02-13 10:24 UTC, vnikolova commented on topics/handle-requests-and-generate-responses.topic
> +                    <path>src/main/kotlin/com.example</path>
Hm I notice now that IntelliJ displays `com.example` when the view is __Project__ and `com/example` when it is __Project Files__. Maybe we can replace these instructions with more generic ones? Or do we want to include intelliJ-specific instructions as well?

For example: 
"Inside `src/main/kotlin/com/example` create a new directory called "model"."

2024-02-14 07:49 UTC, e5l commented on topics/handle-requests-and-generate-responses.topic
> +                    <path>src/main/kotlin/com.example</path>
lgtm

2024-02-14 07:49 UTC, e5l commented on topics/handle-requests-and-generate-responses.topic
> +    <chapter title="Iteration 1: Display static HTML content" id="iteration-1">
yep, sounds good

2024-04-02 12:48 UTC, merged