KTOR-7186 Improve the docs by showcasing broadcasting messages to WebSocket clients via SharedFlow
ktorio/ktor-documentation pull request #495
Opened 2024-07-14 16:13 UTC by mbakgun

This pull request updates the WebSocket documentation to introduce a more efficient method of handling multiple WebSocket sessions using SharedFlow. The new approach offers improved scalability and concurrency management for applications dealing with numerous WebSocket connections.
Key changes:

1. Introduces the use of SharedFlow for broadcasting messages
2. Provides a complete code example demonstrating the implementation
3. Explains the benefits of this approach over manual connection management

This update aims to provide Ktor users with best practices for implementing WebSocket broadcasting in a scalable manner.
Relevant links:
https://youtrack.jetbrains.com/issue/KTOR-7186

2024-07-15 10:01 UTC, vnikolova requested changes
Thanks for the PR, @mbakgun ! Can you address the comment and add some short instructions to the `README.md` file on how to test the code?

2024-07-15 11:14 UTC, mbakgun commented on codeSnippets/snippets/tutorial-websockets-server/src/main/kotlin/com/example/plugins/MessageResponse.kt
> +import kotlinx.serialization.Serializable
Done 👁️

2024-07-17 17:33 UTC, vnikolova approved these changes

2024-07-17 17:34 UTC, merged

2024-07-17 17:37 UTC, vnikolova commented
PR merged 🎊  I renamed the sample folder, as it is no longer connected to a tutorial.
Thanks once again for the contribution @mbakgun !